markdown: redcarpet
base-url: /sandbox
exclude:
  - 'tmp'
  - 'foo'
  - 'README.md'

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "superscript", "underline"]

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
