base-url: /sandbox

exclude:
  - 'tmp'
  - 'foo'
  - 'README.md'

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "superscript", "underline"]

gems:
  - jekyll-mentions
  - jekyll-redirect-from
  - jemoji

### Markdown Processors
kramdown:
  input: GFM
